name: Build and Release

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Tag'
        required: true 

jobs:
  build:
    strategy:
      matrix:
        device: [d2s]
    runs-on: ubuntu-24.04

    steps:
      - name: "⏰Set Time Zone to Beijing"
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: "🚄Set up build environment"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl git

      - name: "⭐Checkout repository with submodules"
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "💡 Setup KernelSU-Next"
        run: |
          if [ -d "./KernelSU-Next" ]; then rm -rf "./KernelSU-Next"; fi
          if [ -d "./drivers/KernelSU-Next" ]; then rm -rf "./drivers/KernelSU-Next"; fi
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs

      - name: "😄 Setup and Apply susfs4ksu Patches"
        run: |
          set -e

          git clone https://github.com/Star-Seven/susfs4ksu -b kernel-4.14 susfs4ksu-repo

          #cp susfs4ksu-repo/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
          cp susfs4ksu-repo/kernel_patches/50_add_susfs_in_kernel-4.14.patch ./
          cp -r susfs4ksu-repo/kernel_patches/fs/* ./fs/
          cp -r susfs4ksu-repo/kernel_patches/include/linux/* ./include/linux/
          #cd ./KernelSU-Next
          #patch -p1 -F 3 < 10_enable_susfs_for_ksu.patch || { echo "Failed to apply patch"; exit 1; }
          #cd ..
          patch -p1 -F 3 < 50_add_susfs_in_kernel-4.14.patch || { echo "Failed to apply patch"; exit 1; }

          echo "Successfully applied susfs4ksu patches"

      - name: "🐎Build for specific device"
        run: ./build.sh -m ${{ matrix.device }} -k y

      - name: "💫Prepare ZIP files for upload"
        run: |
          mkdir -p ${{ github.workspace }}/build/out/zip_files
          find ${{ github.workspace }}/build/out/ -type f -name "*.zip" -exec cp {} ${{ github.workspace }}/build/out/zip_files/ \;

      - name: "😎Upload ZIP files as artifact"
        uses: actions/upload-artifact@v4
        with:
         name: "👍${{ matrix.device }}-KernelSU-Susfs"
         path: ${{ github.workspace }}/build/out/zip_files/

  release:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: "⭐Download all artifacts"
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: "❤️ Create release"
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: "Kernelsu-Next-Susfs-${{ github.event.inputs.tag }}"
          draft: false
          prerelease: false        
          artifacts: "artifacts/**/*.zip"
          body: " Commit SHA: ${{ github.sha }}\n\n**Installation:**\n- Flash the kernel from this version.\n- Download and install KernelSU Next Manager APK from：[KernelSU-Next](https://github.com/rifsxd/KernelSU-Next/releases/latest)\n- Download and install the SuSFS module from：[ksu_module_susfs](https://github.com/sidex15/susfs4ksu-module/releases/latest)"
